<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;netstandard2.0;net462</TargetFrameworks>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<AnalysisMode>All</AnalysisMode>
		<LangVersion>12.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Title>CacheManager</Title>
		<Authors>MHKarami97</Authors>
		<Description>Easy Cache Manager</Description>
		<Copyright>https://github.com/MHKarami97/CacheManager</Copyright>
		<PackageProjectUrl>https://github.com/MHKarami97/CacheManager</PackageProjectUrl>
		<PackageIcon>icon.jpg</PackageIcon>
		<RepositoryUrl>https://github.com/MHKarami97/CacheManager</RepositoryUrl>
		<RepositoryType>public</RepositoryType>
		<PackageTags>CacheManager</PackageTags>
		<PackageReleaseNotes>CacheManager</PackageReleaseNotes>
		<AssemblyVersion>2.1.1</AssemblyVersion>
		<FileVersion>2.1.1</FileVersion>
		<Version>2.1.1</Version>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>MHKarami97.snk</AssemblyOriginatorKeyFile>
		<PublicSign>true</PublicSign>
		<PackageId>EasyMultiCacheManager</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<ApplicationIcon>..\icon.ico</ApplicationIcon>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<IncludeContentInPack>true</IncludeContentInPack>
		<PackageOutputPath>..\PackagesRelease</PackageOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<DocumentationFile>bin\Debug\CacheManager.xml</DocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<DocumentationFile>bin\Release\CacheManager.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<Compile Update="Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\icon.jpg">
			<Pack>true</Pack>
			<PackagePath></PackagePath>
			<Visible>True</Visible>
		</None>
		<None Include="..\LICENSE.txt">
			<Pack>true</Pack>
			<PackagePath></PackagePath>
			<Visible>True</Visible>
		</None>
		<None Include="..\README.md">
			<Pack>true</Pack>
			<PackagePath></PackagePath>
			<Visible>True</Visible>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AsyncKeyedLock" Version="7.1.8"/>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1"/>
	</ItemGroup>

</Project>
